version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    env_file:
      - .env
    depends_on:
      - pdb
  pdb:
    image: postgres:15.4
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:7.2
    ports:
      - "6379:6379"
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A app.celery.celery_app worker --loglevel=info
    env_file:
      - .env
    depends_on:
      - redis
  beat:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A app.celery.celery_app beat --loglevel=info
    env_file:
      - .env
    depends_on:
      - redis
  flower:
    image: docker.mofid.dev/mher/flower:0.9.7
    command: [ 'flower', '--broker=redis://redis:6379', '--port=5555' ]
    ports:
      - "5557:5555"
    depends_on:
      - redis
volumes:
  postgres_data: