version: '3.9'

services:

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    env_file:
      - .env
    depends_on:
      - pdb

  pdb:
    image: postgres:15.4
    env_file:
      - .env
    ports:
      - "5432:5432"

  redis:
    image: redis:7.2
    ports:
      - "6381:6379"

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A app.celery.celery_app worker --loglevel=info -P eventlet
    env_file:
      - .env
    depends_on:
      - redis

  beat:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A app.celery.celery_app beat --loglevel=info
    env_file:
      - .env
    depends_on:
      - redis