version: '3.9'

services:

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8001:8001
    #env_file:
    #  - ./backend/.env
    #volumes:
    #  - .:/app
    #depends_on:
    #  - redis
    #  - db