name: CI
on:
  push:
    branches:
      - develop
jobs:
  # Label of the container job
  container-job:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-22.04
    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      pdb:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_USER: payam
          POSTGRES_PASSWORD: payam
          POSTGRES_DB: foo
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4
  ci:
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.11" ]
        poetry-version: [ "1.7.1" ]
        os: [ ubuntu-22.04 ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Install dependencies
        run: poetry install
      - name: Wait for Database
        run: |
          wget -O wait-for-it.sh https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh
          chmod +x wait-for-it.sh
          ./wait-for-it.sh -h localhost -p 5432 -t 60
      - name: Run Database Migrations
        run: alembic upgrade head
        env:
          #DATABASE_URL: postgresql://payam:payam@localhost/foo
          POSTGRES_HOST: localhost
          POSTGRES_USER: payam
          POSTGRES_PASSWORD: payam
          POSTGRES_DB: foo
      - name: Run the automated tests
        run: |
          pytest